export const GET_ALL_RECIPES = 'GET_ALL_RECIPES'
export const GET_ALL_DIETS = 'GET_ALL_DIETS'
export const GET_RECIPES_BY_DIETS = 'GET_RECIPES_BY_DIETS'
export const ALPHABETICAL_ORDER = 'ALPHABETICAL_ORDER'
export const SET_RECIPES = 'SET_RECIPES'
export const SET_DIETS = 'SET_DIETS'
export const SET_DIET_FILTER = 'SET_DIET_FILTER'
export const SORT_RECIPES_ACTION = 'SORT_RECIPES_ACTION'
export const SORT_BY_HEALTH_LEVEL = 'SORT_BY_HEALTH_LEVEL'
export const SET_ORDER_BAY = 'SET_ORDER_BAY'
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME'
export const GET_DETAIL_RECIPE = 'GET_DETAIL_RECIPE'


